HF_API_KEY="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"
GROQ_API_KEY="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"
TAVILY_API_KEY="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"
SERPER_API_KEY="5dbb5a8eb11c8d205c2479a1db71c2631a1ca573" 